// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Input
    {
        
        public static SteamVR_Action_Boolean __actions_default_in_InteractUI;
        
        public static SteamVR_Action_Boolean __actions_default_in_Teleport;
        
        public static SteamVR_Action_Boolean __actions_default_in_GrabPinch;
        
        public static SteamVR_Action_Boolean __actions_default_in_GrabGrip;
        
        public static SteamVR_Action_Pose __actions_default_in_Pose;
        
        public static SteamVR_Action_Skeleton __actions_default_in_SkeletonLeftHand;
        
        public static SteamVR_Action_Skeleton __actions_default_in_SkeletonRightHand;
        
        public static SteamVR_Action_Single __actions_default_in_SqueezeLeft;
        
        public static SteamVR_Action_Boolean __actions_default_in_teleportUp;
        
        public static SteamVR_Action_Boolean __actions_default_in_teleportDown;
        
        public static SteamVR_Action_Single __actions_default_in_SqueezeRight;
        
        public static SteamVR_Action_Vector2 __actions_default_in_trackpadLeft;
        
        public static SteamVR_Action_Vector2 __actions_default_in_trackpadRight;
        
        public static SteamVR_Action_Boolean __actions_default_in_touchingLeftTrackpad;
        
        public static SteamVR_Action_Boolean __actions_default_in_touchingRightTrackpad;
        
        public static SteamVR_Action_Boolean __actions_default_in_MenuButtonLeft;
        
        public static SteamVR_Action_Boolean __actions_default_in_MenuButtonRight;
        
        public static SteamVR_Action_Vector3 __actions_default_in_ScrollPadLeft;
        
        public static SteamVR_Action_Vector3 __actions_default_in_ScrollPadRight;
        
        public static SteamVR_Action_Boolean __actions_default_in_DPadNorthLeft;
        
        public static SteamVR_Action_Boolean __actions_default_in_DPadEastLeft;
        
        public static SteamVR_Action_Boolean __actions_default_in_DPadSouthLeft;
        
        public static SteamVR_Action_Boolean __actions_default_in_DPadWestLeft;
        
        public static SteamVR_Action_Boolean __actions_default_in_DPadNorthRight;
        
        public static SteamVR_Action_Boolean __actions_default_in_DPadEastRight;
        
        public static SteamVR_Action_Boolean __actions_default_in_DPadSouthRight;
        
        public static SteamVR_Action_Boolean __actions_default_in_DPadWestRight;
        
        public static SteamVR_Action_Boolean __actions_default_in_DPadMiddleLeft;
        
        public static SteamVR_Action_Boolean __actions_default_in_DPadMiddleRight;
        
        public static SteamVR_Action_Vibration __actions_default_out_Haptic;
        
        public static SteamVR_Action_Vector2 __actions_platformer_in_Move;
        
        public static SteamVR_Action_Boolean __actions_platformer_in_Jump;
        
        public static SteamVR_Action_Vector2 __actions_buggy_in_Steering;
        
        public static SteamVR_Action_Single __actions_buggy_in_Throttle;
        
        public static SteamVR_Action_Boolean __actions_buggy_in_Brake;
        
        public static SteamVR_Action_Boolean __actions_buggy_in_Reset;
        
        public static void Dynamic_InitializeActions()
        {
            SteamVR_Input.__actions_default_in_InteractUI.Initialize();
            SteamVR_Input.__actions_default_in_Teleport.Initialize();
            SteamVR_Input.__actions_default_in_GrabPinch.Initialize();
            SteamVR_Input.__actions_default_in_GrabGrip.Initialize();
            SteamVR_Input.__actions_default_in_Pose.Initialize();
            SteamVR_Input.__actions_default_in_SkeletonLeftHand.Initialize();
            SteamVR_Input.__actions_default_in_SkeletonRightHand.Initialize();
            SteamVR_Input.__actions_default_in_SqueezeLeft.Initialize();
            SteamVR_Input.__actions_default_in_teleportUp.Initialize();
            SteamVR_Input.__actions_default_in_teleportDown.Initialize();
            SteamVR_Input.__actions_default_in_SqueezeRight.Initialize();
            SteamVR_Input.__actions_default_in_trackpadLeft.Initialize();
            SteamVR_Input.__actions_default_in_trackpadRight.Initialize();
            SteamVR_Input.__actions_default_in_touchingLeftTrackpad.Initialize();
            SteamVR_Input.__actions_default_in_touchingRightTrackpad.Initialize();
            SteamVR_Input.__actions_default_in_MenuButtonLeft.Initialize();
            SteamVR_Input.__actions_default_in_MenuButtonRight.Initialize();
            SteamVR_Input.__actions_default_in_ScrollPadLeft.Initialize();
            SteamVR_Input.__actions_default_in_ScrollPadRight.Initialize();
            SteamVR_Input.__actions_default_in_DPadNorthLeft.Initialize();
            SteamVR_Input.__actions_default_in_DPadEastLeft.Initialize();
            SteamVR_Input.__actions_default_in_DPadSouthLeft.Initialize();
            SteamVR_Input.__actions_default_in_DPadWestLeft.Initialize();
            SteamVR_Input.__actions_default_in_DPadNorthRight.Initialize();
            SteamVR_Input.__actions_default_in_DPadEastRight.Initialize();
            SteamVR_Input.__actions_default_in_DPadSouthRight.Initialize();
            SteamVR_Input.__actions_default_in_DPadWestRight.Initialize();
            SteamVR_Input.__actions_default_in_DPadMiddleLeft.Initialize();
            SteamVR_Input.__actions_default_in_DPadMiddleRight.Initialize();
            SteamVR_Input.__actions_default_out_Haptic.Initialize();
            SteamVR_Input.__actions_platformer_in_Move.Initialize();
            SteamVR_Input.__actions_platformer_in_Jump.Initialize();
            SteamVR_Input.__actions_buggy_in_Steering.Initialize();
            SteamVR_Input.__actions_buggy_in_Throttle.Initialize();
            SteamVR_Input.__actions_buggy_in_Brake.Initialize();
            SteamVR_Input.__actions_buggy_in_Reset.Initialize();
        }
        
        public static void Dynamic_InitializeInstanceActions()
        {
            Valve.VR.SteamVR_Input.__actions_default_in_InteractUI = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_InteractUI")));
            Valve.VR.SteamVR_Input.__actions_default_in_Teleport = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_Teleport")));
            Valve.VR.SteamVR_Input.__actions_default_in_GrabPinch = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_GrabPinch")));
            Valve.VR.SteamVR_Input.__actions_default_in_GrabGrip = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_GrabGrip")));
            Valve.VR.SteamVR_Input.__actions_default_in_Pose = ((SteamVR_Action_Pose)(SteamVR_Input_References.GetAction("__actions_default_in_Pose")));
            Valve.VR.SteamVR_Input.__actions_default_in_SkeletonLeftHand = ((SteamVR_Action_Skeleton)(SteamVR_Input_References.GetAction("__actions_default_in_SkeletonLeftHand")));
            Valve.VR.SteamVR_Input.__actions_default_in_SkeletonRightHand = ((SteamVR_Action_Skeleton)(SteamVR_Input_References.GetAction("__actions_default_in_SkeletonRightHand")));
            Valve.VR.SteamVR_Input.__actions_default_in_SqueezeLeft = ((SteamVR_Action_Single)(SteamVR_Input_References.GetAction("__actions_default_in_SqueezeLeft")));
            Valve.VR.SteamVR_Input.__actions_default_in_teleportUp = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_teleportUp")));
            Valve.VR.SteamVR_Input.__actions_default_in_teleportDown = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_teleportDown")));
            Valve.VR.SteamVR_Input.__actions_default_in_SqueezeRight = ((SteamVR_Action_Single)(SteamVR_Input_References.GetAction("__actions_default_in_SqueezeRight")));
            Valve.VR.SteamVR_Input.__actions_default_in_trackpadLeft = ((SteamVR_Action_Vector2)(SteamVR_Input_References.GetAction("__actions_default_in_trackpadLeft")));
            Valve.VR.SteamVR_Input.__actions_default_in_trackpadRight = ((SteamVR_Action_Vector2)(SteamVR_Input_References.GetAction("__actions_default_in_trackpadRight")));
            Valve.VR.SteamVR_Input.__actions_default_in_touchingLeftTrackpad = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_touchingLeftTrackpad")));
            Valve.VR.SteamVR_Input.__actions_default_in_touchingRightTrackpad = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_touchingRightTrackpad")));
            Valve.VR.SteamVR_Input.__actions_default_in_MenuButtonLeft = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_MenuButtonLeft")));
            Valve.VR.SteamVR_Input.__actions_default_in_MenuButtonRight = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_MenuButtonRight")));
            Valve.VR.SteamVR_Input.__actions_default_in_ScrollPadLeft = ((SteamVR_Action_Vector3)(SteamVR_Input_References.GetAction("__actions_default_in_ScrollPadLeft")));
            Valve.VR.SteamVR_Input.__actions_default_in_ScrollPadRight = ((SteamVR_Action_Vector3)(SteamVR_Input_References.GetAction("__actions_default_in_ScrollPadRight")));
            Valve.VR.SteamVR_Input.__actions_default_in_DPadNorthLeft = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_DPadNorthLeft")));
            Valve.VR.SteamVR_Input.__actions_default_in_DPadEastLeft = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_DPadEastLeft")));
            Valve.VR.SteamVR_Input.__actions_default_in_DPadSouthLeft = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_DPadSouthLeft")));
            Valve.VR.SteamVR_Input.__actions_default_in_DPadWestLeft = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_DPadWestLeft")));
            Valve.VR.SteamVR_Input.__actions_default_in_DPadNorthRight = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_DPadNorthRight")));
            Valve.VR.SteamVR_Input.__actions_default_in_DPadEastRight = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_DPadEastRight")));
            Valve.VR.SteamVR_Input.__actions_default_in_DPadSouthRight = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_DPadSouthRight")));
            Valve.VR.SteamVR_Input.__actions_default_in_DPadWestRight = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_DPadWestRight")));
            Valve.VR.SteamVR_Input.__actions_default_in_DPadMiddleLeft = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_DPadMiddleLeft")));
            Valve.VR.SteamVR_Input.__actions_default_in_DPadMiddleRight = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_default_in_DPadMiddleRight")));
            Valve.VR.SteamVR_Input.__actions_default_out_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Input_References.GetAction("__actions_default_out_Haptic")));
            Valve.VR.SteamVR_Input.__actions_platformer_in_Move = ((SteamVR_Action_Vector2)(SteamVR_Input_References.GetAction("__actions_platformer_in_Move")));
            Valve.VR.SteamVR_Input.__actions_platformer_in_Jump = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_platformer_in_Jump")));
            Valve.VR.SteamVR_Input.__actions_buggy_in_Steering = ((SteamVR_Action_Vector2)(SteamVR_Input_References.GetAction("__actions_buggy_in_Steering")));
            Valve.VR.SteamVR_Input.__actions_buggy_in_Throttle = ((SteamVR_Action_Single)(SteamVR_Input_References.GetAction("__actions_buggy_in_Throttle")));
            Valve.VR.SteamVR_Input.__actions_buggy_in_Brake = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_buggy_in_Brake")));
            Valve.VR.SteamVR_Input.__actions_buggy_in_Reset = ((SteamVR_Action_Boolean)(SteamVR_Input_References.GetAction("__actions_buggy_in_Reset")));
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[]
            {
                    Valve.VR.SteamVR_Input.__actions_default_in_InteractUI,
                    Valve.VR.SteamVR_Input.__actions_default_in_Teleport,
                    Valve.VR.SteamVR_Input.__actions_default_in_GrabPinch,
                    Valve.VR.SteamVR_Input.__actions_default_in_GrabGrip,
                    Valve.VR.SteamVR_Input.__actions_default_in_Pose,
                    Valve.VR.SteamVR_Input.__actions_default_in_SkeletonLeftHand,
                    Valve.VR.SteamVR_Input.__actions_default_in_SkeletonRightHand,
                    Valve.VR.SteamVR_Input.__actions_default_in_SqueezeLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_teleportUp,
                    Valve.VR.SteamVR_Input.__actions_default_in_teleportDown,
                    Valve.VR.SteamVR_Input.__actions_default_in_SqueezeRight,
                    Valve.VR.SteamVR_Input.__actions_default_in_trackpadLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_trackpadRight,
                    Valve.VR.SteamVR_Input.__actions_default_in_touchingLeftTrackpad,
                    Valve.VR.SteamVR_Input.__actions_default_in_touchingRightTrackpad,
                    Valve.VR.SteamVR_Input.__actions_default_in_MenuButtonLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_MenuButtonRight,
                    Valve.VR.SteamVR_Input.__actions_default_in_ScrollPadLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_ScrollPadRight,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadNorthLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadEastLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadSouthLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadWestLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadNorthRight,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadEastRight,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadSouthRight,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadWestRight,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadMiddleLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadMiddleRight,
                    Valve.VR.SteamVR_Input.__actions_default_out_Haptic,
                    Valve.VR.SteamVR_Input.__actions_platformer_in_Move,
                    Valve.VR.SteamVR_Input.__actions_platformer_in_Jump,
                    Valve.VR.SteamVR_Input.__actions_buggy_in_Steering,
                    Valve.VR.SteamVR_Input.__actions_buggy_in_Throttle,
                    Valve.VR.SteamVR_Input.__actions_buggy_in_Brake,
                    Valve.VR.SteamVR_Input.__actions_buggy_in_Reset};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.SteamVR_Action_In[]
            {
                    Valve.VR.SteamVR_Input.__actions_default_in_InteractUI,
                    Valve.VR.SteamVR_Input.__actions_default_in_Teleport,
                    Valve.VR.SteamVR_Input.__actions_default_in_GrabPinch,
                    Valve.VR.SteamVR_Input.__actions_default_in_GrabGrip,
                    Valve.VR.SteamVR_Input.__actions_default_in_Pose,
                    Valve.VR.SteamVR_Input.__actions_default_in_SkeletonLeftHand,
                    Valve.VR.SteamVR_Input.__actions_default_in_SkeletonRightHand,
                    Valve.VR.SteamVR_Input.__actions_default_in_SqueezeLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_teleportUp,
                    Valve.VR.SteamVR_Input.__actions_default_in_teleportDown,
                    Valve.VR.SteamVR_Input.__actions_default_in_SqueezeRight,
                    Valve.VR.SteamVR_Input.__actions_default_in_trackpadLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_trackpadRight,
                    Valve.VR.SteamVR_Input.__actions_default_in_touchingLeftTrackpad,
                    Valve.VR.SteamVR_Input.__actions_default_in_touchingRightTrackpad,
                    Valve.VR.SteamVR_Input.__actions_default_in_MenuButtonLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_MenuButtonRight,
                    Valve.VR.SteamVR_Input.__actions_default_in_ScrollPadLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_ScrollPadRight,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadNorthLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadEastLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadSouthLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadWestLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadNorthRight,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadEastRight,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadSouthRight,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadWestRight,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadMiddleLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadMiddleRight,
                    Valve.VR.SteamVR_Input.__actions_platformer_in_Move,
                    Valve.VR.SteamVR_Input.__actions_platformer_in_Jump,
                    Valve.VR.SteamVR_Input.__actions_buggy_in_Steering,
                    Valve.VR.SteamVR_Input.__actions_buggy_in_Throttle,
                    Valve.VR.SteamVR_Input.__actions_buggy_in_Brake,
                    Valve.VR.SteamVR_Input.__actions_buggy_in_Reset};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.SteamVR_Action_Out[]
            {
                    Valve.VR.SteamVR_Input.__actions_default_out_Haptic};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[]
            {
                    Valve.VR.SteamVR_Input.__actions_default_out_Haptic};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[]
            {
                    Valve.VR.SteamVR_Input.__actions_default_in_Pose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[]
            {
                    Valve.VR.SteamVR_Input.__actions_default_in_InteractUI,
                    Valve.VR.SteamVR_Input.__actions_default_in_Teleport,
                    Valve.VR.SteamVR_Input.__actions_default_in_GrabPinch,
                    Valve.VR.SteamVR_Input.__actions_default_in_GrabGrip,
                    Valve.VR.SteamVR_Input.__actions_default_in_teleportUp,
                    Valve.VR.SteamVR_Input.__actions_default_in_teleportDown,
                    Valve.VR.SteamVR_Input.__actions_default_in_touchingLeftTrackpad,
                    Valve.VR.SteamVR_Input.__actions_default_in_touchingRightTrackpad,
                    Valve.VR.SteamVR_Input.__actions_default_in_MenuButtonLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_MenuButtonRight,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadNorthLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadEastLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadSouthLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadWestLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadNorthRight,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadEastRight,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadSouthRight,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadWestRight,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadMiddleLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadMiddleRight,
                    Valve.VR.SteamVR_Input.__actions_platformer_in_Jump,
                    Valve.VR.SteamVR_Input.__actions_buggy_in_Brake,
                    Valve.VR.SteamVR_Input.__actions_buggy_in_Reset};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[]
            {
                    Valve.VR.SteamVR_Input.__actions_default_in_SqueezeLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_SqueezeRight,
                    Valve.VR.SteamVR_Input.__actions_buggy_in_Throttle};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[]
            {
                    Valve.VR.SteamVR_Input.__actions_default_in_trackpadLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_trackpadRight,
                    Valve.VR.SteamVR_Input.__actions_platformer_in_Move,
                    Valve.VR.SteamVR_Input.__actions_buggy_in_Steering};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[]
            {
                    Valve.VR.SteamVR_Input.__actions_default_in_ScrollPadLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_ScrollPadRight};
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[]
            {
                    Valve.VR.SteamVR_Input.__actions_default_in_SkeletonLeftHand,
                    Valve.VR.SteamVR_Input.__actions_default_in_SkeletonRightHand};
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.SteamVR_Action_In[]
            {
                    Valve.VR.SteamVR_Input.__actions_default_in_InteractUI,
                    Valve.VR.SteamVR_Input.__actions_default_in_Teleport,
                    Valve.VR.SteamVR_Input.__actions_default_in_GrabPinch,
                    Valve.VR.SteamVR_Input.__actions_default_in_GrabGrip,
                    Valve.VR.SteamVR_Input.__actions_default_in_SqueezeLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_teleportUp,
                    Valve.VR.SteamVR_Input.__actions_default_in_teleportDown,
                    Valve.VR.SteamVR_Input.__actions_default_in_SqueezeRight,
                    Valve.VR.SteamVR_Input.__actions_default_in_trackpadLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_trackpadRight,
                    Valve.VR.SteamVR_Input.__actions_default_in_touchingLeftTrackpad,
                    Valve.VR.SteamVR_Input.__actions_default_in_touchingRightTrackpad,
                    Valve.VR.SteamVR_Input.__actions_default_in_MenuButtonLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_MenuButtonRight,
                    Valve.VR.SteamVR_Input.__actions_default_in_ScrollPadLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_ScrollPadRight,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadNorthLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadEastLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadSouthLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadWestLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadNorthRight,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadEastRight,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadSouthRight,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadWestRight,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadMiddleLeft,
                    Valve.VR.SteamVR_Input.__actions_default_in_DPadMiddleRight,
                    Valve.VR.SteamVR_Input.__actions_platformer_in_Move,
                    Valve.VR.SteamVR_Input.__actions_platformer_in_Jump,
                    Valve.VR.SteamVR_Input.__actions_buggy_in_Steering,
                    Valve.VR.SteamVR_Input.__actions_buggy_in_Throttle,
                    Valve.VR.SteamVR_Input.__actions_buggy_in_Brake,
                    Valve.VR.SteamVR_Input.__actions_buggy_in_Reset};
        }
    }
}
