// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default_In : Valve.VR.SteamVR_Action_List
    {
        
        public Valve.VR.SteamVR_Action_Boolean InteractUI;
        
        public Valve.VR.SteamVR_Action_Boolean Teleport;
        
        public Valve.VR.SteamVR_Action_Boolean GrabPinch;
        
        public Valve.VR.SteamVR_Action_Boolean GrabGrip;
        
        public Valve.VR.SteamVR_Action_Pose Pose;
        
        public Valve.VR.SteamVR_Action_Skeleton SkeletonLeftHand;
        
        public Valve.VR.SteamVR_Action_Skeleton SkeletonRightHand;
        
        public Valve.VR.SteamVR_Action_Single SqueezeLeft;
        
        public Valve.VR.SteamVR_Action_Boolean teleportUp;
        
        public Valve.VR.SteamVR_Action_Boolean teleportDown;
        
        public Valve.VR.SteamVR_Action_Single SqueezeRight;
        
        public Valve.VR.SteamVR_Action_Vector2 trackpadLeft;
        
        public Valve.VR.SteamVR_Action_Vector2 trackpadRight;
        
        public Valve.VR.SteamVR_Action_Boolean touchingLeftTrackpad;
        
        public Valve.VR.SteamVR_Action_Boolean touchingRightTrackpad;
        
        public Valve.VR.SteamVR_Action_Boolean MenuButtonLeft;
        
        public Valve.VR.SteamVR_Action_Boolean MenuButtonRight;
        
        public Valve.VR.SteamVR_Action_Vector3 ScrollPadLeft;
        
        public Valve.VR.SteamVR_Action_Vector3 ScrollPadRight;
        
        public Valve.VR.SteamVR_Action_Boolean DPadNorthLeft;
        
        public Valve.VR.SteamVR_Action_Boolean DPadEastLeft;
        
        public Valve.VR.SteamVR_Action_Boolean DPadSouthLeft;
        
        public Valve.VR.SteamVR_Action_Boolean DPadWestLeft;
        
        public Valve.VR.SteamVR_Action_Boolean DPadNorthRight;
        
        public Valve.VR.SteamVR_Action_Boolean DPadEastRight;
        
        public Valve.VR.SteamVR_Action_Boolean DPadSouthRight;
        
        public Valve.VR.SteamVR_Action_Boolean DPadWestRight;
        
        public Valve.VR.SteamVR_Action_Boolean DPadMiddleLeft;
        
        public Valve.VR.SteamVR_Action_Boolean DPadMiddleRight;
    }
}
